logging:
        level: INFO
        loggers:
        br.mack: DEBUG

        database:
        driverClass: org.h2.Driver
        user: sa
        password:
        url: jdbc:h2:~/test
        validationQuery: "SELECT 1"